const { Schema, model } = require('mongoose');

const SARECORDSchema = new Schema({
  recno: { type: Number },
  job_order: { type: String },
  dept: { type: String },
  customer: { type: String },
  sku_no: { type: String },
  mfg_code: { type: String },
  vndr_style: { type: String },
  ven_code: { type: String },
  mnemonic: { type: String },
  class_12: { type: String },
  class_34: { type: String },
  desc: { type: String },
  desc2: { type: String },
  date: { type: Date },
  detail: { type: String },
  detail_cap: { type: String },
  qty: { type: Number },
  qty_order: { type: Number },
  weight: { type: Number },
  precious: { type: Number },
  cprecious: { type: Number },
  cost: { type: Number },
  price: { type: Number },
  retail: { type: Number },
  msrp: { type: Number },
  item: { type: String },
  sold: { type: Boolean },
  normalsale: { type: Boolean },
  period: { type: String },
  saleloc: { type: String },
  taxstatus: { type: String },
  taxstat2: { type: String },
  taxstat3: { type: String },
  clerk1: { type: String },
  comm_rate1: { type: Number },
  check1: { type: Boolean },
  clerk2: { type: String },
  comm_rate2: { type: Number },
  check2: { type: Boolean },
  clerk3: { type: String },
  comm_rate3: { type: Number },
  check3: { type: Boolean },
  clerk4: { type: String },
  comm_rate4: { type: Number },
  check4: { type: Boolean },
  clerk5: { type: String },
  comm_rate5: { type: Number },
  check5: { type: Boolean },
  specialord: { type: Boolean },
  memosale: { type: Boolean },
  compdeduct: { type: Boolean },
  polled: { type: Boolean },
  mod_date: { type: Date },
  mod_second: { type: Date },
  store_id: { type: String },
  qbid: { type: String },
  qbseq: { type: String },
  qbadd: { type: Boolean },
  qbmod: { type: Boolean },
  img_exists: { type: Boolean },
  chkfield: { type: String },
  store_code: { type: String },
});

const SARECORD = model('SARECORD', SARECORDSchema, 'SARECORD');

module.exports = SARECORD;
